version: "3.7"
services: 
    db: 
        container_name: postgres-accounts
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: accounts-db
        build:
            context: .
            dockerfile: ./db/Dockerfile
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '8082:5432'
    web:
        image: accounts-web
        depends_on: 
            - db
        ports: 
            - '8081:8080'
        volumes:
            - .:/usr/src/app
