version: "3.7"
services: 
    db: 
        image: postgres
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: notification-db
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '8087:5432'
    web:
        image: notification-web
        depends_on: 
            - db
        ports: 
            - '8086:8080'
        volumes:
            - .:/usr/src/app
