version: "3.3"
services: 
    # db: 
    #     container_name: postgres
    #     environment: 
    #         POSTGRES_PASSWORD: postgres
    #         POSTGRES_USER: postgres
    #         POSTGRES_DB: medical-conditions-db
    #     volumes: 
    #         - ./pgdata:/var/lib/postgresql/data
    #     build:
    #         context: .
    #         dockerfile: ./db/Dockerfile
    #     ports:
    #         - '8081:5432'
    web:
        image: medical-conditions-web
        # depends_on: 
        #     - db
        ports: 
            - '8080:8080'
        volumes:
            - .:/usr/src/app
