version: "3.7"
services: 
    db: 
        image: postgres
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: business-metrics-db
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '8084:5432'
    web:
        image: business-metrics-web
        depends_on: 
            - db
        ports: 
            - '8083:8080'
        volumes:
            - .:/usr/src/app
