version: "3.7"
services: 
    db: 
        container_name: postgres-patient-record
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: patient-record-db
        build:
            context: .
            dockerfile: ./db/Dockerfile
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '8088:5432'
    web:
        image: patient-record-web
        depends_on: 
            - db
        ports: 
            - '8087:8080'
        volumes:
            - .:/usr/src/app
